/**
 * Pegel-Online API
 * API für das bundesweite Messstellennetz der Wasserstraßen- und Schifffahrtsverwaltung des Bundes.  Die API stellt drei verschiedene Ressourcen zur Verfügung: __Station__, __Measurement__, __Water__. ### Authentifizierung / Autorisierung / API Limitierung Es ist keine Authentifizierung oder Autorisierung notwendig. Aktuell besteht keine API Limitierung. ### Allgemeine Query-Parameter Zusätzlich zu den angegebenen Parametern sind ebenfalls allgemeine Parameter für alle Schnittstellen verfügbar ([Dokumentation](https://www.pegelonline.wsv.de/webservice/dokuRestapi;jsessionid=A294589CCEF6630142D2589F49BFA2EC#urlParameter)). - `charset`: Gibt die Kodierung der Response an. Standard ist hier _UTF-8_. Möglich ist z.B. auch _ISO-8859-1_. - `prettyprint`: Kann die zur besseren Lesbarkeit standardmäßig aktivierte Teilung der Response in mehreren Zeilen deaktivieren: _prettyprint=false_. Diese Einstellung wird für den produktiven Einsatz empfohlen. - `limit/offset`: Einschränkung der Anzahl der Ergebnisse. Hiermit kann \'Pagination\' realisiert werden. `limit` gibt dabei die Anzahl der zurückgegebenen Elemente an. `offset` ermöglicht einen Offset vom Startwert. Beispiel: _limit=10&offset=20_ bedeutet, dass 10 Elemente beginnend mit dem 21. Element zurückgegeben werden.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrentMeasurement } from '../model/CurrentMeasurement';
import { TimeseriesGaugeZero } from '../model/TimeseriesGaugeZero';

export class Timeseries {
  /**
   * Kurzbezeichnung
   */
  'shortname'?: string;
  /**
   * Langbezeichnung
   */
  'longname'?: string;
  /**
   * Maßeinheit
   */
  'unit'?: string;
  /**
   * Abstand der Messwerte in Minuten.
   */
  'equidistance'?: number;
  'currentMeasurement'?: CurrentMeasurement;
  'gaugeZero'?: TimeseriesGaugeZero;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  'characteristicValues'?: Array<any>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'shortname',
      baseName: 'shortname',
      type: 'string',
      format: '',
    },
    {
      name: 'longname',
      baseName: 'longname',
      type: 'string',
      format: '',
    },
    {
      name: 'unit',
      baseName: 'unit',
      type: 'string',
      format: '',
    },
    {
      name: 'equidistance',
      baseName: 'equidistance',
      type: 'number',
      format: 'float',
    },
    {
      name: 'currentMeasurement',
      baseName: 'currentMeasurement',
      type: 'CurrentMeasurement',
      format: '',
    },
    {
      name: 'gaugeZero',
      baseName: 'gaugeZero',
      type: 'TimeseriesGaugeZero',
      format: '',
    },
    {
      name: 'characteristicValues',
      baseName: 'characteristicValues',
      type: 'Array<any>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Timeseries.attributeTypeMap;
  }

  public constructor() {}
}
